#!/bin/sh

[ "$PROTO_TYPE" = "ipv4" ] || exit

run()
{
    [ "$VERBOSE" = "0" ] || echo $@
    $@
}


if [ "$PHASE" = "pre-up" ] ; then
    # Since we have an IPv4 address configured, we clear them
    run ip addr flush dev $IFACE
fi

if [ "$PHASE" = "up" ] ; then
    if [ "$PROTO_METHOD" = "static" ] ; then
        run ip addr add $PROTO_ADDRESS dev $IFACE 
    fi
fi

