#!/bin/bash

set -e
source ../functions.sh

# Handle only bridges
[ "$IFACE_TYPE" = "bridge" ] || exit 0


if [ "$PHASE" = "pre-up" ] ; then
    run ip link add name $IFACE type bridge
fi


if [ "$PHASE" = "post-down" ] ; then
    run ip link delete dev $IFACE
fi


