#!/bin/sh

run()
{
    [ "$VERBOSE" = "0" ] || echo $@
    $@
}

if [ "$IFACE_TYPE" = "bridge" ] ; then
    if [ "$PHASE" = "pre-up" ] ; then
        run ip link add dev $IFACE type bridge
    fi

    if [ "$PHASE" = "up" ] ; then
        run ip link set dev $IFACE up
    fi

    if [ "$PHASE" = "down" ] ; then
        run ip link set dev $IFACE down
    fi

    if [ "$PHASE" = "post-down" ] ; then
        run ip link del dev $IFACE
    fi
fi


